### PR TITLE
Improving clang formatting

### PR DESCRIPTION
**Pull request by juanangp**
juanangp Ok: 87 [](https://gitlab.cern.ch/rest-for-physics/framework/-/commits/clang-script)

Script `reformat-clang` has been improved:
- Added `readlink` to make the script independent from the path where is launched
- Adding support for single files including file extensions `*.h`, `*.cxx`, `*.cc` and `*.C`
- Now the script check if the file or directory exists
- Removing un-necessary commands

**Added  `githook` in the `cmake`, so the `clang-format` is performed when `git commit` is issued**
- `githook` is created when `cmake` is issued and if there is no `pre-commit` present.
- Check if `clang-format` is present in the system, otherwise is skipped.
- Can be used as template to add different `githook` features.

### CODE REVIEW

**Review by lobis — APPROVED** [review]

**Review by jgalan — APPROVED** [review]
As I commented to @lobis it would be interesting that our `Cmake` system forces that `reformat-clang.sh` is executed at the beginning of each `make` execution. So that any user that launches code compilation keeps a good formatting.

**Comment by lobis** [comment]
> As I commented to @lobis it would be interesting that our `Cmake` system forces that `reformat-clang.sh` is executed at the beginning of each `make` execution. So that any user that launches code compilation keeps a good formatting.

It could be nice but maybe it would give problems, also it takes a fair amount of time to execute the clang-format. It would be annoying for users such as me that have this done automatically on file save. I think it may be better a step on the pipeline that gives error if the source files have not been clang-formatted? (calculating the diff etc.).

What do you think @jgalan @juanangp ?

**Comment by juanangp** [comment]
> What do you think @jgalan @juanangp ?
Perhaps would be better to use a pre-commit hook https://stackoverflow.com/questions/55965712/how-do-i-add-clang-formatting-to-pre-commit-hook
But I am not sure how to implement it in the repo...

**Comment by lobis** [comment]
> > What do you think @jgalan @juanangp ?
> > Perhaps would be better to use a pre-commit hook https://stackoverflow.com/questions/55965712/how-do-i-add-clang-formatting-to-pre-commit-hook
> > But I am not sure how to implement it in the repo...

It is not possible to implement it in the repo, at most you can have a file in the repo and direct users to copy this file into their `.git` folder.

**Comment by juanangp** [comment]
> It is not possible to implement it in the repo, at most you can have a file in the repo and direct users to copy this file into their `.git` folder.
Can this be done at the build or in the cmake? Or this is an overkill? Also note that you need `clang-format` installed in your OS

**Pull request merged**
