### PR TITLE
New logos updated

### PR DESCRIPTION
**Pull request by jgalan**
Improved logo and uploaded source powerpoint files.

### CODE REVIEW

**Review by lobis — COMMENTED** [review]
I think we should have the main logo in SVG format.

**Comment by jgalan** [comment]
> I think we should have the main logo in SVG format.

Ok, just add it

**Comment by lobis** [comment]
> > I think we should have the main logo in SVG format.
> 
> Ok, just add it

Its not possible to convert png to svg since its a vector format, but it is possible to convert svg to png. Vector formats allow for unlimited zoom as they consist of geometrical shapes instead of pixels and are the best format for logos, since all the other pixelized formats can be derived from it.

We would need to redraw the logo using a program like Inkscape, I could do it if you want, but it will not look 100% identical to the original.

**Comment by jgalan** [comment]
The original file is in PPT, cannot be transformed to SVG?

**Comment by lobis** [comment]
> The original file is in PPT, cannot be transformed to SVG?

Good Idea. I will upload the logos in SVG.

**Review by lobis — CHANGES_REQUESTED** [review]
Upload logos in SVG

**Review by lobis — APPROVED** [review]

**Pull request merged**
