### PR TITLE
GitHub Actions CI pipeline and Dockerfile with dependencies

### PR DESCRIPTION
**Pull request by lobis**

### CODE REVIEW

**Comment by lobis** [comment]
Working CI with github actions: check for dependencies on base image and building REST with all submodules and with default configuration (no compilation flags).

**Comment by lobis** [comment]
Also a new Dockerfile has been added into https://github.com/rest-for-physics/framework/blob/lobis-patch-1/pipeline/dockerfiles/base/Dockerfile, which contains all the required dependencies for REST.

For convinience I have uploaded an image here: https://hub.docker.com/repository/docker/lobis/root-geant4-garfieldpp/general so that you just need to `docker pull lobis/root-geant4-garfieldpp` to get the image. However keep in mind that this repository in dockerhub is not automatically synced with the Dockerfile (but this Dockerfile shouldn't change much).

**Comment by jgalan** [comment]
One thing I do not understand from this pull-request it is why at the files changed there are updates at the submodules.

**Comment by lobis** [comment]
> One thing I do not understand from this pull-request it is why at the files changed there are updates at the submodules.

This is a mistake, I must have done a `git add --all` at some point and for some reason the submodules were different from master. I will revert this change.

**Comment by jgalan** [comment]
Yes, please, don't use `git add -all`.

**Comment by nkx111** [comment]
> For convinience I have uploaded an image here: https://hub.docker.com/repository/docker/lobis/root-geant4-garfieldpp/general s 

What's the difference between this image and the already using image `nkx1231/root6-geant4-garfield`?

**Comment by lobis** [comment]
> What's the difference between this image and the already using image `nkx1231/root6-geant4-garfield`?

In this image I am using the ROOT official docker image, which is something that came out recently. I also use Ubuntu 20.04 and (I think) newer verion of some dependencies (such as gcc) that was giving us problems.

> So by adding this file `.github/workflows/ci.yml` CI pipeline can be automatically established on github? just like `.gitlab-ci.yml` for gitlab?

Yes, GitHub has free runners, but the number of minutes per month is limited, you can see the file I uploaded to see how it works, its a bit different from the GitLab since it uses actions, which are quite powerful tools.

**Comment by nkx111** [comment]
>  I also use Ubuntu 20.04 and (I think) newer verion of some dependencies (such as gcc) that was giving us problems.

but the old image is also of old version(ubuntu 16.04, gcc 5.4.0, root 6.10.08, geant4 10.4.p02)

**Comment by jgalan** [comment]
I believe the old image will not compile with c++14? We had problems already some time ago, at LFNA we were running the pipelines with the shell mode, not docker image mode.

On the other hand, the problem I see with this pull-request is the mesh with unrelated things being committed.

@lobis Not sure what is the best solution, but perhaps creating a new branch and doing cherry-pick of basic commits?

```
git checkout development
git checkout -b new_branch
git cherry-pick xxxx
git cherry-pick xxxx
```

Then, modify each cherry-pick commit (if necessary) before pushing to the new remote `new_branch`

```
git HEAD~
// Do whatever changes
git commit -c ORIG_HEAD
```

**Comment by lobis** [comment]
> I believe the old image will not compile with c++14? We had problems already some time ago, at LFNA we were running the pipelines with the shell mode, not docker image mode.
> 
> On the other hand, the problem I see with this pull-request is the mesh with unrelated things being committed.
> 
> @lobis Not sure what is the best solution, but perhaps creating a new branch and doing cherry-pick of basic commits?
> 
> ```
> git checkout development
> git checkout -b new_branch
> git cherry-pick xxxx
> git cherry-pick xxxx
> ```
> 
> Then, modify each cherry-pick commit (if necessary) before pushing to the new remote `new_branch`
> 
> ```
> git reset HEAD~
> // Do whatever changes
> git commit -c ORIG_HEAD
> ```

Yes, I was planning on cleaning the commits. However I was thinking of only removing the ones that modify the submodules

**Comment by jgalan** [comment]
> > I believe the old image will not compile with c++14? We had problems already some time ago, at LFNA we were running the pipelines with the shell mode, not docker image mode.
> > On the other hand, the problem I see with this pull-request is the mesh with unrelated things being committed.
> > @lobis Not sure what is the best solution, but perhaps creating a new branch and doing cherry-pick of basic commits?
> > ```
> > git checkout development
> > git checkout -b new_branch
> > git cherry-pick xxxx
> > git cherry-pick xxxx
> > ```
> > 
> > 
> > Then, modify each cherry-pick commit (if necessary) before pushing to the new remote `new_branch`
> > ```
> > git reset HEAD~
> > // Do whatever changes
> > git commit -c ORIG_HEAD
> > ```
> 
> Yes, I was planning on cleaning the commits. However I was thinking of only removing the ones that modify the submodules

Right, I thats what I mean, modify (or remove) only the commits that have modified the submodules.

**Comment by jgalan** [comment]
Now there is a lot of cmake self generated configuration and output automatic generated files, as `CINT_xxx` I imagine those do not need to be added...

**Comment by lobis** [comment]
> Now there is a lot of cmake self generated configuration and output automatic generated files, as `CINT_xxx` I imagine those do not need to be added...

Yes, I am having a bit of trouble cleaning this lol

**Comment by lobis** [comment]
I think I may have accidentally deleted some changes @jgalan made, hopefully it was only to change the Docker image name.

**Comment by jgalan** [comment]
> > Now there is a lot of cmake self generated configuration and output automatic generated files, as `CINT_xxx` I imagine those do not need to be added...
> 
> Yes, I am having a bit of trouble cleaning this lol
> 
> I think I will just create a new branch

Yes, thats the easiest solution I believe. At the new branch, inheriting from `development` just `cherry-pick` the "good" commits, and in addition `cherry-pick` the "bad" commits and modify them, re-commiting them with `git reset HEAD~` ... `git commit -c ORIG_HEAD`, if you believe it is appropiate to just modify the "bad" commits.

**Comment by lobis** [comment]
> > > Now there is a lot of cmake self generated configuration and output automatic generated files, as `CINT_xxx` I imagine those do not need to be added...
> > 
> > 
> > Yes, I am having a bit of trouble cleaning this lol
> > I think I will just create a new branch
> 
> Yes, thats the easiest solution I believe. At the new branch, inheriting from `development` just `cherry-pick` the "good" commits, and in addition `cherry-pick` the "bad" commits and modify them, re-commiting them with `git reset HEAD~` ... `git commit -c ORIG_HEAD`, if you believe it is appropiate to just modify the "bad" commits.

It should be done now, I think this can be safely merged, but please have a look just in case.

**Review by jgalan — APPROVED** [review]
Perfect!

**Pull request merged**
