### PR TITLE
TRestBrowser added event selection bar

### PR DESCRIPTION
**Pull request by nkx111**
nkx111 Medium: 148 [](https://gitlab.cern.ch/rest-for-physics/framework/-/commits/nkx111-patch-5) [](https://github.com/rest-for-physics/framework/commits/nkx111-patch-5)

Added event selection bar at bottom to quickly jump events. No need to manually input event id anymore. The selection is applied on AnalysisTree observables through `TTreeFormula`.

image

### CODE REVIEW

**Comment by jgalan** [comment]
On the other hand, there is any difference between `--`, `++` and `Previous Event` `Next Event`? I imagine `--` and `++` operates on single signals? single hits? single tracks?

**Review by jgalan — APPROVED** [review]

**Comment by nkx111** [comment]
> On the other hand, there is any difference between `--`, `++` and `Previous Event` `Next Event`? I imagine `--` and `++` operates on single signals? single hits? single tracks?

Yes, `++`, `--` means to switch between signals.

**Comment by nkx111** [comment]
> Interesting the `TTreeFormula` I guess the method `Bool_t TRestAnalysisTree::EvaluateCut(const string cut)` could be improved and simplified using that?

Yes, it is possible.

**Comment by jgalan** [comment]
Approuve plz!

**Review by lobis — APPROVED** [review]

**Pull request merged**
