### PR TITLE
Pull submodules exclude

### PR DESCRIPTION
**Pull request by jgalan**
A simple patch at `pull-submodules.py` so that we are allowed to specify submodules that should be ignored trhough the command line.

I.e. the following command will avoid pulling geant4lib, restG4 and axionlib.

```
python3 pull-submodules.py --exclude:geant4lib,restG4,axionlib
```

In principle, it will also apply to submodules from submodules. So the following command will pull `axionlib` excluding the internal submodule `SolarAxionFlux` which contains big size data.

```
python3 pull-submodules.py --exclude:solarAxionFlux
```

### CODE REVIEW

**Comment by juanangp** [comment]
Looks fine to me, perhaps just to update the instructions to exclude axionlib and others?

Also, do we understand why the CI is failing

**Comment by lobis** [comment]
> Looks fine to me, perhaps just to update the instructions to exclude axionlib and others?
> 
> Also, do we understand why the CI is failing

The failing CI is due to a problem with the docker image on my end, I updated the new name for the image, but need you to approve my merge requests @jgalan @juanangp (or whoever wants to)

**Review by lobis — APPROVED** [review]
Looks fine

**Comment by jgalan** [comment]
> > Looks fine to me, perhaps just to update the instructions to exclude axionlib and others?
> > Also, do we understand why the CI is failing
> 
> The failing CI is due to a problem with the docker image on my end, I updated the new name for the image, but need you to approve my merge requests @jgalan @juanangp (or whoever wants to)

Sorry, I didnt realice I had to review asap. Perhaps we could leave a message at the description or something

Such as **"Please, review and approve as soon as possible ASAP"**

**Comment by jgalan** [comment]
In any case, I guess I need to merge that branch into this one.

**Comment by jgalan** [comment]
> Looks fine to me, perhaps just to update the instructions to exclude axionlib and others?

Ok, I just added a minor update at the README.md

**Review by juanangp — APPROVED** [review]

**Pull request merged**
