### PR TITLE
Adding foreach to pull-submodules.py

### PR DESCRIPTION
**Pull request by juanangp**
juanangp Ok: 48 [](https://gitlab.cern.ch/rest-for-physics/framework/-/commits/pullforeach) [](https://github.com/rest-for-physics/framework/commits/pullforeach)

Added `git submodule foreach` to `pull-submodules.py` script:
- Avoids multiple request to github that might cause issues in unizar firewall
- Speed up the checkout of the submodules

Note that the overall behaviour of `pull-submodules.py` has not been significatively changed, however note that  `git submodule foreach` acts on all the submodules that have been initialized.

### CODE REVIEW

**Comment by jgalan** [comment]
I did a quick test of the pulling process, but it seems the output has been strongly affected

**Comment by jgalan** [comment]
This is how it looks in master

Screenshot 2022-10-26 at 18 15 19

**Comment by juanangp** [comment]
> This is how it looks in master
> 
> Screenshot 2022-10-26 at 18 15 19
Indeed, the output now is tricky because `git submodule foreach` gets the info for all the submodules at the same time.

I have changed it, now it gets the info at the different steps and it prints the hast after it is done, see below:
image

**Review by jgalan — APPROVED** [review]

**Comment by jgalan** [comment]
This PR needs approval

**Pull request merged**
