### PR TITLE
Jgalan pull submodules exclude

### PR DESCRIPTION
**Pull request by jgalan**
The was a small bug since `exclude_elems` was not initialized. The pipeline was failing.

### CODE REVIEW

**Comment by jgalan** [comment]
Hi @lobis , the pipeline is failing at the build stage.

[pipeline status](https://gitlab.cern.ch/rest-for-physics/framework/-/commits/jgalan_pull_submodules_exclude)

Could you have a look, and place the right docker images at this branch?

**Review by juanangp — APPROVED** [review]

**Comment by lobis** [comment]
> Hi @lobis , the pipeline is failing at the build stage.
> 
> [pipeline status](https://gitlab.cern.ch/rest-for-physics/framework/-/commits/jgalan_pull_submodules_exclude)
> 
> Could you have a look, and place the right docker images at this branch?

So the problem is that you are not using the full tag name: `lobis/root-geant4-garfieldpp:cxx14_ROOTv6-25-01_Geant4v10.4.3`, instead it is using `lobis/root-geant4-garfieldpp`, which is taken as the `latest` tag, which I don't think exists.

I am not sure why this is happening since on the branch `jgalan_pull_submodules_exclude`, the image seems correct, but on the `master` it is not, I guess its the merge?

**Comment by jgalan** [comment]
What do you mean? It says it is using the following image for `build` and `build_latest`.

```
Using Docker executor with image lobis/root-geant4-garfieldpp:cxx14_ROOTv6-25-01_Geant4v10.4.3 ...
```

and for `build_latest_root622_geant4v1042`

```
Pulling docker image lobis/root-geant4-garfieldpp:cxx14_ROOTv6-22-08_Geant4v10.4.2 ...
```

I don't see what master has to do with all this.

The development branch is failing the same way it is doing this branch `jgalan_pull_submodules_exclude`.

https://gitlab.cern.ch/rest-for-physics/framework/-/jobs/13897241

I dont know why it is failing, but looks `build_nkx` is building properly.

**Comment by lobis** [comment]
> What do you mean? It says it is using the following image for `build` and `build_latest`.
> 
> ```
> Using Docker executor with image lobis/root-geant4-garfieldpp:cxx14_ROOTv6-25-01_Geant4v10.4.3 ...
> ```
> 
> and for `build_latest_root622_geant4v1042`
> 
> ```
> Pulling docker image lobis/root-geant4-garfieldpp:cxx14_ROOTv6-22-08_Geant4v10.4.2 ...
> ```
> 
> I don't see what master has to do with all this.
> 
> The development branch is failing the same way it is doing this branch `jgalan_pull_submodules_exclude`.
> 
> https://gitlab.cern.ch/rest-for-physics/framework/-/jobs/13897241
> 
> I dont know why it is failing, but looks `build_nkx` is building properly.

Yes, you are right, it has nothing to do with master, my bad.

I think it is failing because of this:

image

Which is what I believed to have fixed with the latest changes to geant4lib. Perhaps it is not using the version of geant4lib that implements this changes?

**Comment by jgalan** [comment]
The pipeline is loading the geant4 version as follows:

```
before_script:
  - pwd
  - export USER="test"
    #  - export GIT_SSL_NO_VERIFY=1
  - echo $CI_SERVER_HOST
  - echo $CRONJOB
    # We redefine the HOME
  - export HOME=${CI_PROJECT_DIR}/install/
  - if [ -d $HOME/.rest ]; then rm -Rf $HOME/.rest; fi
  - if [ -f "/opt/root/install/bin/thisroot.sh" ]; then source /opt/root/install/bin/thisroot.sh; fi
  - root-config --version
  - if [ -f "/opt/geant4/install/bin/geant4.sh" ]; then source /opt/geant4/install/bin/geant4.sh; fi
  - geant4-config --version
  - if [ -d "/opt/garfieldpp/install" ]; then export GARFIELD_HOME=/opt/garfieldpp/install; fi
  - if [ -d "/opt/garfieldpp/install" ]; then export HEED_DATABASE=$GARFIELD_HOME/Heed/heed++/database; fi
  - if [ -d "/opt/garfieldpp/install" ]; then export LD_LIBRARY_PATH=$GARFIELD_HOME/lib:$LD_LIBRARY_PATH; fi
  - ls $GARFIELD_HOME
  - python3 --version
  - apt update && apt install -y wget
```

**Comment by jgalan** [comment]
Ok, we have again a framework validation pipeline back and operative.

Please, I believe the most efficient option is to keep that stable, and that we all keep maintaining a common pipeline structure. **So, let's fix GitLab + nkx docker image as the official REST CI.**

We have spent lots of energy, time and efforts to have this validation pipeline running. Including many hours debugging, developing, or deploying a running GitLab system at LFNA, and CERN.

Any changes on that "stable" GitLab+nkx should be well justified, and discussed at `rest-forum.unizar.es`, so that we all agree to move to a new scheme, and make it clear that the effort is worth.

I want people gets the habit to create tests for validation for any new code, it will be hard to make that coherent if we have different platforms with slightly different coding formats, and people new to this world needs to get adapted to new staff.

On top of that GitLab pipeline is running, we dedicated many hours to make it running, so the most natural would be that we would stick to that.

Of course, I believe it is interesting to add new `builds` with additional docker images with more modern ROOT versions or compilation standards, so that we make sure we are able to compile REST with the latest, but we are also capable to keep REST compatible with older versions. 

Please, approve the merge asap.

**Review by juanangp — APPROVED** [review]

**Review by DavidDiezIb — APPROVED** [review]

**Pull request merged**
