### PR TITLE
TRestRun::TRestRun(string) constructor supports both root file and rml file initialization.

### PR DESCRIPTION
**Pull request by nkx111**
nkx111  [](https://gitlab.cern.ch/rest-for-physics/framework/-/commits/nkx111-patch-2)

TRestRun::TRestRun(string) constructor supports both root file and rml file initialization.

### CODE REVIEW

**Comment by jgalan** [comment]
It is a bit strange the problem at the pipeline, `libRestCore.so`, `libRestEvents.so` and `libRestMetadata` do not exist since a long time, how it is possible that now there is any mention to them?

```
Error in <TUnixSystem::FindDynamicLibrary>: libRestMetadata.so does not exist in /builds/rest-for-physics/framework/install_latest/lib:/usr/local/geant4/install/lib:/usr/local/root/install/lib:/usr/local/geant4/install/lib:/usr/local/garfieldpp/install/lib:/usr/local/garfieldpp/install/lib:/usr/lib/x86_64-linux-gnu:/usr/local/garfieldpp/install/lib:.:/usr/local/root/install/lib:/usr/lib/x86_64-linux-gnu/tls/haswell/avx512_1/x86_64:/usr/lib/x86_64-linux-gnu/tls/haswell/avx512_1:/usr/lib/x86_64-linux-gnu/tls/haswell/x86_64:/usr/lib/x86_64-linux-gnu/tls/haswell:/usr/lib/x86_64-linux-gnu/tls/avx512_1/x86_64:/usr/lib/x86_64-linux-gnu/tls/avx512_1:/usr/lib/x86_64-linux-gnu/tls/x86_64:/usr/lib/x86_64-linux-gnu/tls:/usr/lib/x86_64-linux-gnu/haswell/avx512_1/x86_64:/usr/lib/x86_64-linux-gnu/haswell/avx512_1:/usr/lib/x86_64-linux-gnu/haswell/x86_64:/usr/lib/x86_64-linux-gnu/haswell:/usr/lib/x86_64-linux-gnu/avx512_1/x86_64:/usr/lib/x86_64-linux-gnu/avx512_1:/usr/lib/x86_64-linux-gnu/x86_64:/usr/lib/x86_64-linux-gnu
[1440](https://gitlab.cern.ch/rest-for-physics/framework/-/jobs/20593505#L1440)
```

**Comment by jgalan** [comment]
I have created a branch `nkx111-patch-2` at restG4 removing the libraries from `Validate.C`

**Comment by jgalan** [comment]
Screenshot 2022-03-26 at 12 16 43

It is a bit strange that $GARFIELD_HOME is pointing to the framework directory.

**Comment by lobis** [comment]
> Screenshot 2022-03-26 at 12 16 43
> 
> It is a bit strange that $GARFIELD_HOME is pointing to the framework directory.

`GARFIELD_HOME` is a variable used by old Garfield installations, it should not appear anywhere, its probably defined by the pipeline somewhere. Now the correct variable is `GARFIELD_INSTALL`.

**Comment by lobis** [comment]
> 

I have no idea to be honest, but it also appears on some other recent pipelines such as https://gitlab.cern.ch/rest-for-physics/restg4/-/pipelines/3764122. Perhaps when we merge https://github.com/rest-for-physics/framework/pull/129 it gets fixed? No idea.

**Comment by jgalan** [comment]
The problem was something else, the pipeline was already fixed.

**Comment by lobis** [comment]
> The problem was something else, the pipeline was already fixed.

What was the problem @jgalan ? I also still have this problem at https://github.com/rest-for-physics/restG4/pull/35 and no idea how to fix it.

**Comment by jgalan** [comment]
Commits a3f0b6f and  3e629ab

**Comment by jgalan** [comment]
The problem with `libRestCore.so`, `libRestEvents.so` and `libRestMetadata.so` it is solved in this commit f48d6b213beb541f123616003be3fac7a077b3b5

It is just a warning I believe, since we were not experiencing problems before.

The errors you are getting, may be precision issues. See for example the pipeline error you are getting

```
    if (en != 245699) {
        cout << "Error in total energy" << endl;
        return 8;
    }
```

it is the pipeline passing locally? If not, check the value of `en`.

Probably the best would be to rewrite that piece of code as:

```
    if (en != 245699) {
        cout << "Error in total energy" << endl;
        cout << "The total energy is: " << en << " will it should be : " << 245699 << endl;
        return 8;
    }
```

**Comment by jgalan** [comment]
I believe this PR could be un-drafted and ready for review.

**Comment by lobis** [comment]
> The problem with `libRestCore.so`, `libRestEvents.so` and `libRestMetadata.so` it is solved in this commit [rest-for-physics/restG4@f48d6b2](https://github.com/rest-for-physics/restG4/commit/f48d6b213beb541f123616003be3fac7a077b3b5).
> 
> You may `git cherry-pick f48d6b2` in your branch to get it into [rest-for-physics/restG4#35](https://github.com/rest-for-physics/restG4/pull/35)
> 
> It is just a warning I believe, since we were not experiencing problems before.
> 
> The errors you are getting at [rest-for-physics/restG4#35](https://github.com/rest-for-physics/restG4/pull/35) , may be precision issues. See for example the pipeline error you are getting
> 
> ```
>     if (en != 245699) {
>         cout << "Error in total energy" << endl;
>         return 8;
>     }
> ```
> 
> it is the pipeline passing locally? If not, check the value of `en`.
> 
> Probably the best would be to rewrite that piece of code as:
> 
> ```
>     if (en != 245699) {
>         cout << "Error in total energy" << endl;
>         cout << "The total energy is: " << en << " will it should be : " << 245699 << endl;
>         return 8;
>     }
> ```
> 
> Actually I see the value is being printed, and now it is not 245699, but 245700. This change of precision will probably affect other pipelines. Perhaps few eV loss in previous Geant4 version that do not produce any loss in the new version?

The Geant4 version is the same as before, I just made some updates to support latest versions, which may have unintended effects on the physics, such as this one.

**Review by jgalan — APPROVED** [review]

**Review by lobis — APPROVED** [review]

**Pull request merged**
