### PR TITLE
Fix bug when processing files with a single event

### PR DESCRIPTION
**Pull request by nkx111**
nkx111 Ok: 40 [](https://gitlab.cern.ch/rest-for-physics/framework/-/commits/nkx111-single-event-file) [](https://github.com/rest-for-physics/framework/commits/nkx111-single-event-file)

Issue #390.
The bug comes from when finished doing test run(before the actual event processing), REST will push-forward to the next event. Since there is only one event in the file, find the next non-existing event will actually trigger finish reading. Therefore the later processes will get null input event, and cause problems. This fix it to prevent push-forward of event entries during test run, if test run succeeds.

### CODE REVIEW

**Comment by jgalan** [comment]
Nice! I guess some pipelines are failing because it is not the same event that it is being evaluated?

**Comment by juanangp** [comment]
> Nice! I guess some pipelines are failing because it is not the same event that it is being evaluated?

Still don't understand why some pipelines are failing, if you are checking a different event why only one observable has a different value e.g. on the TREX-DM validation pipeline? I would expect several observables failing...

**Comment by jgalan** [comment]
> > Nice! I guess some pipelines are failing because it is not the same event that it is being evaluated?
> 
> Still don't understand why some pipelines are failing, if you are checking a different event why only one observable has a different value e.g. on the TREX-DM validation pipeline? I would expect several observables failing...

The observable that it is failing is `rate_MeanRate_InHz` this observable does not only depend on the specific entry being evaluated but it takes the timestamp value of a different event (shifted by 10 events, for example) to calculate the mean value. If there is an extra event ahead this value could be affected. This is a guess.

For the ray-tracing case, all the values are changing, so I guess it is an issue affecting the seed by the fact that there is one more event entry? @nkx111 ?

**Comment by juanangp** [comment]
> rate_MeanRate_InHz

Then this observable doesn't make much sense to me, in general we should have one observable per event, the rate can be computed later on...

**Comment by nkx111** [comment]
> The observable that it is failing is rate_MeanRate_InHz

I looked into each timestamp of the first 10 events from the pipeline. It changes after this PR. I suspect that it is related somehow with the bug in TRestRawMultiFEMINOSToSignalProcess we already recorded. https://github.com/rest-for-physics/rawlib/issues/36

Before the PR:
```
$test run: 1582141590.00456

$event 0: 1582141590.00629
$event 1: 1582141590.00456
$event 2: 1582141590.00629
$event 3: 1582141590.00627
$event 4: 1582141590.0068
$event 5: 1582141590.00771
$event 6: 1582141590.00961
...
```

With this PR:
```
$test run: 1582141590.00456

$event 0: 1582141590.00456
$event 1: 1582141590.00456
$event 2: 1582141590.00629
$event 3: 1582141590.00627
$event 4: 1582141590.0068
$event 5: 1582141590.00771
$event 6: 1582141590.00961
```

The assumed "correct behavior" is that the first two events from `TRestRawMultiFEMINOSToSignalProcess` is identical, which is exactly the case with this PR. Before this PR, however, with additional "get-next-event" operation called after test run, event id 0 mysteriously turns into event id 2. 

Anyway, despite the first few values of `rate_MeanRate_InHz`, this observable is correct and meaningful. I think we can just update the checks. In future when we fix the bug in `TRestRawMultiFEMINOSToSignalProcess`, the validation file shall be updated again.

**Comment by nkx111** [comment]
> For the ray-tracing case, all the values are changing, so I guess it is an issue affecting the seed by the fact that there is a different looping scheme?

Yes, I think this is the case. Previously we are calling `TRestAxionGeneratorProcess::ProcessEvent()` once more than this PR. So the random value gets changed.

**Comment by jgalan** [comment]
> > rate_MeanRate_InHz
> 
> Then this observable doesn't make much sense to me, in general we should have one observable per event, the rate can be computed later on...

Yes, that might be a good choice. But does that mean that we need to move `https://sultan.unizar.es/rest/classTRestEventRateAnalysisProcess.html` to legacy?

**Review by juanangp — APPROVED** [review]

**Review by jgalan — APPROVED** [review]

**Pull request merged**
