### PR TITLE
156 remove using namespace std from header files

### PR DESCRIPTION
**Pull request by lobis**
Large lobis  [](https://gitlab.cern.ch/rest-for-physics/framework/-/commits/156-remove-using-namespace-std-from-header-files)

Implements https://github.com/rest-for-physics/framework/issues/156.

@rest-for-physics/core_dev

Sadly I made the mistake to base my branch on https://github.com/rest-for-physics/framework/tree/cmake-ctest, but since this branch is waiting to be merged to master, the changes list will soon be simplified.

### CODE REVIEW

**Comment by jgalan** [comment]
56 files changed - 64 commits - 1 line at the PR description. It is not a nightmare for any reviewer?

**Comment by lobis** [comment]
> 56 files changed - 64 commits - 1 line at the PR description. It is not a nightmare for any reviewer?
> 
> Likely we should try to follow the strategy to divide PR, not to merge them.

yes, thats why I mentioned I accidentally based this branch on `cmake-ctest` :(

**Comment by lobis** [comment]
I have this wierd problem with `TRestReflector`

image

I can't find where this `type_info` and `typeinfo` classes / structs are defined and don't know why this didn't give an error before, any ideas @nkx111 ?

**Comment by lobis** [comment]
Changes were implemented in https://github.com/rest-for-physics/framework/pull/168, closing this PR due to duplicate.

**Pull request closed without merging**
