### PR TITLE
Adding submodule validation inside framework

### PR DESCRIPTION
**Pull request by juanangp**
juanangp Ok: 60 [](https://gitlab.cern.ch/rest-for-physics/framework/-/commits/submodule-validation) [](https://github.com/rest-for-physics/framework/commits/submodule-validation)

Issues found on submodule validation pipelines after a merge inside master https://github.com/rest-for-physics/framework/pull/368

Adding submodule validation inside framework

Contributes to https://github.com/rest-for-physics/framework/issues/372

### CODE REVIEW

**Comment by jgalan** [comment]
Great I see it is already working here!

**Comment by jgalan** [comment]
Pipeline should succeed once the following PRs are merged:

https://github.com/rest-for-physics/rawlib/pull/95

https://github.com/rest-for-physics/framework/pull/370

**Comment by juanangp** [comment]
Pipeline is stuck in ´GeneralFit.C´ @lobis can u approve #370

**Review by jgalan — APPROVED** [review]

**Review by lobis — APPROVED** [review]

**Comment by juanangp** [comment]
@lobis looks like all submodule validations are failing due to the latest PR to master https://github.com/rest-for-physics/framework/pull/376

It seems that these lines are problematic inside the submodule validation.
```
Run cd $GITHUB_WORKSPACE
  cd $GITHUB_WORKSPACE
  curl https://raw.githubusercontent.com/rest-for-physics/framework/master/scripts/validatePreCommitConfig.py | python
  shell: bash --noprofile --norc -e -o pipefail {0}
  env:
    CMAKE_BUILD_TYPE: Release
    REST_PATH: /rest/wimplib/install
    BRANCH_NAME: submodule-validation
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  [2](https://github.com/rest-for-physics/framework/actions/runs/4173229886/jobs/7225311146#step:5:2)611  100  2611    0     0  11627      0 --:--:-- --:--:-- --:--:-- 116[5](https://github.com/rest-for-physics/framework/actions/runs/4173229886/jobs/7225311146#step:5:5)[6](https://github.com/rest-for-physics/framework/actions/runs/4173229886/jobs/7225311146#step:5:6)
fatal: detected dubious ownership in repository at '/__w/framework/framework'
To add an exception for this directory, call:

	git config --global --add safe.directory /__w/framework/framework
Comparing files with branch= in the framework repository.
WARNING: The file .pre-commit-config.yaml is different from the one in the framework repository (branch=).
WARNING: The file .clang-format is different from the one in the framework repository (branch=).
WARNING: The file .cmake-format.yaml is different from the one in the framework repository (branch=).
Error: Process completed with exit code 1.
```
I have added some changes in submodule validation, please check https://github.com/rest-for-physics/wimplib/pull/6/commits/d75b74b6503a0884a5e338df5ae5a46be7598945

Let me know if you agree with these changes, validation is passing for wimplib, so I can implement in other submodule pipelines.

**Comment by juanangp** [comment]
> I have added some changes in submodule validation, please check [rest-for-physics/wimplib@d75b74b](https://github.com/rest-for-physics/wimplib/commit/d75b74b6503a0884a5e338df5ae5a46be7598945)

Better check the latest changes on https://github.com/rest-for-physics/wimplib/pull/6 not I have moved the pre-commit config validation to a separate job.

**Pull request merged**
