### PR TITLE
Format rml files in a similar way as clang format

### PR DESCRIPTION
**Pull request by lobis**
lobis Ok: 50 [](https://gitlab.cern.ch/rest-for-physics/framework/-/commits/205-format-rml-files-in-a-similar-way-as-clang-format)

Fixes https://github.com/rest-for-physics/framework/issues/205

### CODE REVIEW

**Comment by juanangp** [comment]
Shall we drop the support for directories in this script? I think, shouldn't bee necessary after implementing `hooks` #209

**Comment by juanangp** [comment]
Shall we drop the support for directories in this script? I think, shouldn't bee necessary after implementing `hooks` #209

**Comment by lobis** [comment]
> Shall we drop the support for directories in this script? I think, shouldn't bee necessary after implementing `hooks` #209

I don't think so, people (like me) would still want to use it for formatting the whole project tree, and I cannot use this cmake hook due to remote build :(

**Comment by juanangp** [comment]
> I don't think so, people (like me) would still want to use it for formatting the whole project tree, and I cannot use this cmake hook due to remote build :(

Ok, fair enough

**Review by juanangp — APPROVED** [review]

**Review by jgalan — APPROVED** [review]

**Pull request merged**
