### PR TITLE
Simplifying opening of TRestRun and TRestDataSet files

### PR DESCRIPTION
**Pull request by juanangp**
juanangp Ok: 68 [](https://github.com/rest-for-physics/framework/commits/restroot_update)

Simplifiying `restRoot` behaviour for opening `TRestRun` and `TRestDataSet`
- Reimplementing TRestAnalysisTree, TRestEvent and metadata objects in a dedicated macro `REST_LoadInputFiles.C`
- Droping support for multiple files, now only one `TRestRun` and/or `TRestDataSet` can be opened (the first one)
- If the file is not a `TRestRun` or a `TRestDataSet` it just use default `root` behaviour using `TRint`
- Now the flag to load macros is just  `--m` instead of `--m 1` since the latest is misleading and error prone.

### CODE REVIEW

**Comment by jgalan** [comment]
But `analysisTree`, `eventTree` and metadata objects have been removed from the automatic instances  ... I find them handy. 

It is not better to simplify it in #441?

**Comment by juanangp** [comment]
> But `analysisTree`, `eventTree` and metadata objects have been removed from the automatic instances ... I find them handy.
> 
> I agree you simplify things, but without removing functionalities.
> 
> It is not better to simplify it in #441?

Ok, now the opening of input files is done using a macro, I didn't implement metadata  yet

**Comment by juanangp** [comment]
> > But `analysisTree`, `eventTree` and metadata objects have been removed from the automatic instances ... I find them handy.
> > I agree you simplify things, but without removing functionalities.
> > It is not better to simplify it in #441?
> 
> Ok, now the opening of input files is done using a macro, I didn't implement metadata yet

Now metadata objects are also implemented, note that this PR is pointing to #441 instead of master. Please, do this merge before merging #441 in master.

**Review by jgalan — APPROVED** [review]

**Comment by jgalan** [comment]
Perhaps this PR can be merged directly to master? Don't see why we should merge to #441

**Pull request merged**
