### PR TITLE
TRestReflector. Updating hot compilation flags

### PR DESCRIPTION
**Pull request by jgalan**
jgalan Ok [](https://gitlab.cern.ch/rest-for-physics/framework/-/commits/testing)

Trying to solve pipeline at rest-for-physics/rawlib#51

### CODE REVIEW

**Comment by juanangp** [comment]
Would not be better to also cherry-pick https://github.com/rest-for-physics/rawlib/pull/51/commits/ee15907d61b4d37e9b557ae0ea11d7faa1d89b90 to see if the pipeline suceed?

I have done this on https://github.com/rest-for-physics/rawlib/tree/pipeline-patch and https://github.com/rest-for-physics/framework/tree/pipeline-patch to see if the pipeline suceed.
But I see that you have done something similar, let me know which PR you prefer

**Comment by jgalan** [comment]
> Would not be better to also cherry-pick [rest-for-physics/rawlib@ee15907](https://github.com/rest-for-physics/rawlib/commit/ee15907d61b4d37e9b557ae0ea11d7faa1d89b90) to see if the pipeline suceed?
> 
> I have done this on https://github.com/rest-for-physics/rawlib/tree/pipeline-patch and https://github.com/rest-for-physics/framework/tree/pipeline-patch to see if the pipeline suceed. But I see that you have done something similar, let me know which PR you prefer

Yes, I just implememted what you proposed at the other PR.

**Comment by jgalan** [comment]
But the branch at the framework must be created with the same name as the branch at rawlib, so that the rawlib pipeline pulls the branch `testing` at framework.

>> Would not be better to also cherry-pick https://github.com/rest-for-physics/rawlib/commit/ee15907d61b4d37e9b557ae0ea11d7faa1d89b90 to see if the pipeline suceed?

Yes, not sure why the docker was not already updated.

**Comment by jgalan** [comment]
However, rest-for-physics/rawlib#51 already contains commit rest-for-physics/rawlib@ee15907 . rest-for-physics/rawlib#51  cannot be merged, then other PR just merge the new master?

**Comment by juanangp** [comment]
> However, [rest-for-physics/rawlib#51](https://github.com/rest-for-physics/rawlib/pull/51) already contains commit [rest-for-physics/rawlib@ee15907](https://github.com/rest-for-physics/rawlib/commit/ee15907) . [rest-for-physics/rawlib#51](https://github.com/rest-for-physics/rawlib/pull/51) cannot be merged? then after merging other PR just merge the new master?

Yes, I think  it can be merged

**Comment by jgalan** [comment]
Ok, just this PR should be approved before merging! @lobis

**Review by juanangp — APPROVED** [review]

**Review by lobis — APPROVED** [review]

**Pull request merged**
