### PR TITLE
Update framework validation with restG4

### PR DESCRIPTION
**Pull request by juanangp**
juanangp Ok: 3 [](https://gitlab.cern.ch/rest-for-physics/framework/-/commits/validation_framework) [](https://github.com/rest-for-physics/framework/commits/validation_framework)

As stated on https://github.com/rest-for-physics/restG4/pull/103 `restG4` validation is not present on framework pipeline. This PR is meant to add `restG4` validation workflow to `framework`

Related PR https://github.com/rest-for-physics/restG4/pull/104

### CODE REVIEW

**Review by lobis — APPROVED** [review]

**Review by jgalan — APPROVED** [review]

**Comment by jgalan** [comment]
There is an issue with a validation test with example 08.alphas. My guess is that the following PR affected the restG4 validation https://github.com/rest-for-physics/geant4lib/pull/102

**Comment by jgalan** [comment]
> My guess is that the issue was introduced here #387

I don't see how that PR can make only fail the phi angle, while the theta angle is correct.

**Comment by jgalan** [comment]
I just reverted https://github.com/rest-for-physics/framework/pull/387 locally, recompiled, and tested the example, it still fails.

**Comment by jgalan** [comment]
The 08.alphas example succeeded on 20th/March --> https://github.com/rest-for-physics/restG4/actions/runs/4471734464/jobs/7857133162?pr=102

**Comment by juanangp** [comment]
Why this PR have been merged and the related PR https://github.com/rest-for-physics/restG4/pull/104 is not?

Note that after it is merged we should change:
```
  restG4-validation:
    uses: rest-for-physics/restG4/.github/workflows/validation.yml@validation_framework
```
To 
```
  restG4-validation:
    uses: rest-for-physics/restG4/.github/workflows/validation.yml@master
```

**Pull request merged**
