### PR TITLE
Added preprocessor definition via cmake STRING

### PR DESCRIPTION
**Pull request by lobis**
lobis Ok: 7 [](https://gitlab.cern.ch/rest-for-physics/framework/-/commits/lobis-regex-lib-compile-def)

Related to https://rest-forum.unizar.es/t/detectorlib-implementation-problem-inside-the-rawlib-process/535/5

Adding definitions via CMake which appear only when corresponding libraries are selected to compile. This is useful when we want to have code in one library that uses another library that may or may not be available.

I tried to look for where this was being defined previously in the code but didn't find it (for any library) I guess it was removed at some point and never cause problems.

### CODE REVIEW

**Comment by jgalan** [comment]
Ok, it seems to be working nice.

The only thing is, how the DEBUG statement works? Perhaps its behaviour is related to the cmake version?

```
Empty submodule dir: packages/restSQL. Option: REST_SQL=OFF
-- making build files in /home/jgalan/rest-framework/source/libraries/axion, dependency: 
-- 20 source files in total, 20 classes to generete, 0 additional source files
DEBUGAdding compile definition: REST_AxionLib
-- making build files in /home/jgalan/rest-framework/source/libraries/detector, dependency: 
-- 37 source files in total, 37 classes to generete, 0 additional source files
DEBUGAdding compile definition: REST_DetectorLib
```

**Review by jgalan — DISMISSED** [review]

**Comment by lobis** [comment]
> Ok, it seems to be working nice.
> 
> The only thing is the output is a bit distorted, how the DEBUG statement works? Perhaps its behaviour is related to the cmake version?
> 
> ```
> Empty submodule dir: packages/restSQL. Option: REST_SQL=OFF
> -- making build files in /home/jgalan/rest-framework/source/libraries/axion, dependency: 
> -- 20 source files in total, 20 classes to generete, 0 additional source files
> DEBUGAdding compile definition: REST_AxionLib
> -- making build files in /home/jgalan/rest-framework/source/libraries/detector, dependency: 
> -- 37 source files in total, 37 classes to generete, 0 additional source files
> DEBUGAdding compile definition: REST_DetectorLib
> ```

https://cmake.org/cmake/help/latest/command/message.html

In my cmake version it works fine, I guess this did not exist in your cmake version and thats why it concatenates the strings. DEBUG messages are intended for developers and not users, in my opinion they are a middle ground between STATUS messages and comments, you can change the DEBUG to STATUS to display the mesage easier than to change it from a comment to a message.

There are many small problems similar to this that can happen due to allowing users to use very old cmake versions, we should change the minimum cmake version but its not possible yet because of https://github.com/rest-for-physics/framework/issues/162, I couldn't fix it. I encourage anyone @rest-for-physics/core_dev to try to fix this issue as I think its a bit critical.

**Review by juanangp — APPROVED** [review]

**Comment by jgalan** [comment]
I woudnt mind that the DEBUG statement is in STATUS statement. Anyway a non-developer user will not look most of the information coming out from cmake.

**Comment by lobis** [comment]
> I woudnt mind that the DEBUG statement is in STATUS statement. Anyway a non-developer user will not look most of the information coming out from cmake.

I made a commit for this and now the reviews have to be made again, I think this is new behavior right? @jgalan @juanangp

**Review by juanangp — APPROVED** [review]

**Review by Andrii01L — APPROVED** [review]

**Comment by jgalan** [comment]
Yes, I was playing with the settings. If someone pushes new commits, then any approval will be removed, which I believe it makes sense, but if you want, we get back to previous setting? @juanangp @lobis ?

**Comment by lobis** [comment]
> Yes, I was playing with the settings. If someone pushes new commits, then any approval will be removed, which I believe it makes sense, but if you want, we get back to previous setting? @juanangp @lobis ?

I think it makes sense, I agree 👍

**Pull request merged**
