### PR TITLE
pull-submodules.py minor update

### PR DESCRIPTION
**Pull request by jgalan**
jgalan Ok: 1 [](https://gitlab.cern.ch/rest-for-physics/framework/-/commits/pull_modules_minor_fix)

I think we had to add the following patch in order to get the latest remote. If not, the local master branch was not always synced. Recently remarked by @KonradAltenmueller

### CODE REVIEW

**Review by juanangp — APPROVED** [review]

**Comment by jgalan** [comment]
@lobis @juanangp Any idea why restG4 simulation is failing here? It says something about `ibstdc++.so.6` not being found.

**Comment by juanangp** [comment]
> @lobis @juanangp Any idea why restG4 simulation is failing here? It says something about `ibstdc++.so.6` not being found.

This branch is up-to-date with master? It is strange that is giving this error

**Comment by jgalan** [comment]
Ok, I relaunched the pipeline. A different error is coming out. Since the update on this PR is just that pulls the latest, perhaps we were not testing against the latest `master`?

https://gitlab.cern.ch/rest-for-physics/framework/-/commit/0e9eeb9e2458d6f477d622aa65356994f2465846/pipelines?ref=pull_modules_minor_fix

It is the PandaX-III topology failing now @nkx

**Comment by juanangp** [comment]
> Ok, I relaunched the pipeline. A different error is coming out. Since the update on this PR is just that pulls the latest, perhaps we were not testing against the latest `master`?
> 
> https://gitlab.cern.ch/rest-for-physics/framework/-/commit/0e9eeb9e2458d6f477d622aa65356994f2465846/pipelines?ref=pull_modules_minor_fix
> 
> It is the PandaX-III topology failing now @nkx

That's weird, perhaps some changes in the docker image @lobis

**Comment by lobis** [comment]
> > Ok, I relaunched the pipeline. A different error is coming out. Since the update on this PR is just that pulls the latest, perhaps we were not testing against the latest `master`?
> > https://gitlab.cern.ch/rest-for-physics/framework/-/commit/0e9eeb9e2458d6f477d622aa65356994f2465846/pipelines?ref=pull_modules_minor_fix
> > It is the PandaX-III topology failing now @nkx
> 
> That's weird, perhaps some changes in the docker image @lobis

No, I made changes to the `rest-for-physics` image a few days ago but they are reverted, the image is still the same as before.

**Comment by juanangp** [comment]
I think the issue is because of this PR https://github.com/rest-for-physics/framework/pull/233 which is already merged

```
2022-06-09T09:11:26.3459062Z /__w/framework/framework/framework/source/libraries/axion/src/TRestAxionXrayWindow.cxx:313:38: error: 'class TRestAxionXrayWindow' has no member named 'InstantiateChildMetadata'
2022-06-09T09:11:26.3460140Z   313 |     fMask = (TRestPatternMask*)this->InstantiateChildMetadata("Mask", "mask");
2022-06-09T09:11:26.3460491Z       |                                      ^~~~~~~~~~~~~~~~~~~~~~~~
2022-06-09T09:11:26.5803304Z make[2]: Leaving directory '/__w/framework/framework/framework/build'
2022-06-09T09:11:26.6202534Z [ 57%] Built target RestTrack
2022-06-09T09:11:26.6318561Z make[2]: Entering directory '/__w/framework/framework/framework/build'
2022-06-09T09:11:26.6910184Z [ 57%] generating: /__w/framework/framework/framework/build/rootdict/CINT_TRestRawZeroSuppresionProcess.cxx with /__w/framework/framework/framework/source/libraries/legacy/inc/TRestRawZeroSuppresionProcess.h;/__w/framework/framework/framework/build/rootdict/TRestRawZeroSuppresionProcess_Linkdef.h
2022-06-09T09:11:26.9816357Z make[2]: *** [source/libraries/axion/CMakeFiles/RestAxion.dir/build.make:410: source/libraries/axion/CMakeFiles/RestAxion.dir/src/TRestAxionXrayWindow.cxx.o] Error 1
```

I am working on implementing a pipeline in github to avoid this kind of issues, in fact this error comes from the github workflow that I am working on.

**Pull request merged**
