### PR TITLE
Updating validation file of PandaX-III

### PR DESCRIPTION
**Pull request by jgalan**
jgalan Ok: 0 [](https://gitlab.cern.ch/rest-for-physics/framework/-/commits/jgalan_smear_review2) [](https://github.com/rest-for-physics/framework/commits/jgalan_smear_review2)

Due to update of TRestDetectorHitsSmearingProcess at rest-for-physics/detectorlib#72

### CODE REVIEW

**Comment by jgalan** [comment]
@nkx I had to update the validation file for PandaX-III because I updated the way it is initialised the random generator. I am not 100% sure of the reason why this is like that, but my guess is because now the `random` generator is initialised at `InitProcess` and there are two calls to `new TRandom`. Thus, the first event in the final processing chain is executed just after initialisation. In the previous version I think it was initialised inside `InitFromConfigFile` and thus, the test loop was executing the first random call.

**Comment by lobis** [comment]
Perhaps these files are starting to become too big? The main framework repository is already at `105.69 MB` size. This would increase the total size by ~3%.

**Comment by jgalan** [comment]
> Perhaps these files are starting to become too big? The main framework repository is already at `105.69 MB` size. This would increase the total size by ~3%.

Ups, in fact I was not supposed to upload the Mb file. Only the 13kbytes one, I didn't notice, thanks! I will just push force.

**Comment by jgalan** [comment]
Fixed!

**Review by juanangp — APPROVED** [review]

**Comment by nkx111** [comment]
Looks fine to me

**Review by nkx111 — APPROVED** [review]

**Pull request merged**
