### PR TITLE
TRestRun::GetRunInformation. Protecting method

### PR DESCRIPTION
**Pull request by jgalan**
jgalan  [](https://gitlab.cern.ch/rest-for-physics/framework/-/commits/run_fix)

- Added protection against segmentation fault.

### CODE REVIEW

**Comment by jgalan** [comment]
Hi @nkx. I am experiencing problems with TRestAnalysisPlot when trying to use the `classify` statement and `runTag`. Trying to find the problem I realised that when using the method `TRestRun::GetRunInformation("runTag")` is not finding the run value.

So, if I do `restRoot file.root`, and

```
run0->GetRunInformation("runTag")
```

it will just return `runTag`.

Same for you? Any quick fix?

**Comment by nkx111** [comment]
Can you try to input "fRunTag" to get fRunTag? I guess "runTag" is not the datamember name and cannot be recoginzed.

**Comment by nkx111** [comment]
Maybe we can try to convert the input info name to datamember naming style?

**Review by nkx111 — APPROVED** [review]

**Comment by jgalan** [comment]
Perfect, thanks!

**Pull request merged**
