### PR TITLE
Bump minimum CMake version to 3.16

### PR DESCRIPTION
**Pull request by lobis**
lobis Ok: 13 [](https://gitlab.cern.ch/rest-for-physics/framework/-/commits/lobis-cmake-162)

* Fixes https://github.com/rest-for-physics/framework/issues/162 (more info at https://github.com/rest-for-physics/framework/issues/162#issuecomment-1120187962)
* This PR also introduces minor changes to the testing cmake

### CODE REVIEW

**Comment by juanangp** [comment]
I have found that the required `cmake` version is used in other packages/libraries:
image
Shall we also update them @jgalan @lobis ?

**Comment by jgalan** [comment]
Perhaps we could have a common file at `cmake/` that contains common definitions for any `CMakeLists.txt`

**Comment by lobis** [comment]
> Perhaps we could have a common file at `cmake/` that contains common definitions for any `CMakeLists.txt` and we just use `include( CommonDefinitions)` or similar?

No, we need to have the same line across all the repos if we want to allow the compilation of each library separate from the framework (compile a library using the system installed version of REST). Hopefully this won't change for a while.

**Review by juanangp — APPROVED** [review]

**Comment by lobis** [comment]
@jgalan can you approve this PR please? ty

**Review by jgalan — APPROVED** [review]

**Pull request merged**
