### PR TITLE
New TRestEventRateAnalysisProcess implementation

### PR DESCRIPTION
**Pull request by jgalan**
Large jgalan  [](https://gitlab.cern.ch/rest-for-physics/framework/-/commits/rates)

It adds the new process `TRestEventRateAnalysisProcess` that will serve to monitor the event rate using an analysis tree observable.

This process belongs to the framework, and therefore it will be possible to connect it everywhere in the data processing chain.

The process will be forced to be single threaded so that it solves problems related to issue #126 

After merging to master, the rate observables will be removed from `TRestRawSignalAnalysisProcess`.

@rest-for-physics/core_dev

### CODE REVIEW

**Comment by jgalan** [comment]
@nkx Could you update the pandaxiii data pipeline so that we could remove the observables at `TRestRawSignalAnalysisProcess`?

**Comment by jgalan** [comment]
@nkx I was a bit surprised that I was not able to use `observable="all"` or `verboseLevel="info"` at the `pipeline/trex/01_raw.rml` script.

So, for example, if I remove the following lines from that RML, observables will not be present event if I added `observable="all"`

```
                <observable name="SecondsFromStart" type="double" value="ON" />
                <observable name="HoursFromStart" type="double" value="ON" />
                <observable name="EventTimeDelay" type="double" value="ON" />
                <observable name="MeanRate_InHz" type="double" value="ON" />
```

**Comment by jgalan** [comment]
@nkx I was also a bit surprised of the fact that if I enable the verboseLevel at `TRestEventRateAnalysisProcess` to `info` I don't get the output of `PrintMetadata`.

**Comment by nkx111** [comment]
> @nkx I was a bit surprised that I was not able to use `observable="all"` or `verboseLevel="info"` at the `pipeline/trex/01_raw.rml` script.
> 
> So, for example, if I remove the following lines from that RML, observables will not be present event if I added `observable="all"`
> 
> ```
>                 <observable name="SecondsFromStart" type="double" value="ON" />
>                 <observable name="HoursFromStart" type="double" value="ON" />
>                 <observable name="EventTimeDelay" type="double" value="ON" />
>                 <observable name="MeanRate_InHz" type="double" value="ON" />
> ```
> 
> and if I place `verboseLevel="info"` the PrintMetadata will not be called. I believe it is connected to RML definition since I remember it was working before.

I don't engage this problem. Maybe you need to re-run cmake to compile this process?

**Comment by jgalan** [comment]
> > @nkx I was a bit surprised that I was not able to use `observable="all"` or `verboseLevel="info"` at the `pipeline/trex/01_raw.rml` script.
> > So, for example, if I remove the following lines from that RML, observables will not be present event if I added `observable="all"`
> > ```
> >                 <observable name="SecondsFromStart" type="double" value="ON" />
> >                 <observable name="HoursFromStart" type="double" value="ON" />
> >                 <observable name="EventTimeDelay" type="double" value="ON" />
> >                 <observable name="MeanRate_InHz" type="double" value="ON" />
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and if I place `verboseLevel="info"` the PrintMetadata will not be called. I believe it is connected to RML definition since I remember it was working before.
> 
> I don't engage this problem. Maybe you need to re-run cmake to compile this process?

I recompiled from scratch, I set `verboseLevel` to `info` at `run.xml` and at `01_raw.rml` inside `TRestRawSignalAnalysisProcess` and at `TRestEventRateAnalysisProcess`. But I still do not see `PrintMetadata` of those processes coming out in the output.

```
jgalan@sultan:~/rest-raw/pipeline/trex$ restManager --c 01_raw.rml --f R01928_tagTest_Vm_250_Vd_160_Pr_6_Gain_0x0_Shape_0xF_Clock_0x4-068.aqs 
Warning in <UnknownClass::SetDisplay>: DISPLAY not set, setting it to 87.100.43.135:0.0
Starting pid: 13074
                            
              [==                                  Launching TRestManager...                                   ==]              
                            
              [==                                    Creating TRestManager                                     ==]              
              [==                                            path:.                                            ==]              
MediumMagboltz::LoadGasFile: Reading /home/jgalan/.rest/download/ne_98.0-iC4H10_2.0-E_vs_P_10.0_1000.0_nodes_20-nCol_10-maxE_400.gas.
MediumMagboltz::LoadGasFile: Version 12
MediumMagboltz::LoadGasFile:
    Gas composition set to Ne/iC4H10 (98/2)
-- Info : Downloading remote file : https://sultan.unizar.es/gasFiles/gases.rmlTo local file : /home/jgalan/.rest/download/gases.rmlDownloading remote file : https://sultan.unizar.es/gasFiles/gases.rmlTo local file : /home/jgalan/.rest/download/gases.rmlDownloading remote file : https://sultan.unizar.es/gasFiles//ne_98.0-iC4H10_2.0-E_vs_P_10.0_1000.0_nodes_20-nCol_10-maxE_400.gasTo local file : /home/jgalan/.rest/download/ne_98.0-iC4H10_2.0-E_vs_P_10.0_1000.0_nodes_20-nCol_10-maxE_400.gasTRestDetectorGas. Gas file loaded!
              ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++              
              ||                                    TRestDetectorGas content                                    ||              
              ||                                       Config file : null                                       ||              
              ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++              
              ||                             Name : Neon-Isobutane 2Pct 10-10E3Vcm                              ||              
              ||                        Title : Neon-Isobutane Mixture (2Pct Isobutane)                         ||              
              ||                                     REST Version : 2.3.10                                      ||              
              ||                                   REST Official release: No                                    ||              
              ||                                        Clean state: No                                         ||              
              ||                                     REST Commit : 3f0d4004                                     ||              
              ||                                   REST Library version : 1.5                                   ||              
              ----------------------------------------------------------------------------------------------------              
              ||                                    Status : Gasfile loaded                                     ||              
              ||       Gas filename : ne_98.0-iC4H10_2.0-E_vs_P_10.0_1000.0_nodes_20-nCol_10-maxE_400.gas       ||              
              ||                                        Pressure : 1 atm                                        ||              
              ||                                     Temperature : 293.15 K                                     ||              
              ||                                    Electric Field : 0 V/cm                                     ||              
              ||                                      W-value : 21.3485 eV                                      ||              
-- Info : Calling Garfield directly. Please be aware that the unit is differentfrom REST standard unit. E is V/cm. The return is cm/us
              ||                                   Drift velocity : 0 mm/us                                     ||              
              ||                                 Max. Electron energy : 400 eV                                  ||              
              ||                                     Field grid nodes : 20                                      ||              
              ||                               Efield range : ( 10 , 1000 ) V/cm                                ||              
              ||                                      Number of Gases : 2                                       ||              
              ||                             Gas id : 0, Name : ne, Fraction : 0.98                             ||              
              ||                           Gas id : 1, Name : iC4H10, Fraction : 0.02                           ||              
              ****************************************************************************************************              
                            
                            

-- Info : thread 0: validating process chain
-- Info : general process: rate
              [==                 (external) TRestRawMultiFEMINOSToSignalProcess : virtualDAQ                  ==]              
              [==                   ++ TRestRawSignalChannelActivityProcess : rawChActivity                    ==]              
              [==                           ++ TRestEventRateAnalysisProcess : rate                            ==]              
              [==                          ++ TRestRawSignalAnalysisProcess : rawAna                           ==]              
              ====================================================================================================              
              [==                          TRestProcessRunner: Starting the Process..                          ==]              
-- Info : TRestThread : Writing temp file. Thread id : 0
              [==                           TRestProcessRunner: 100 processed events                           ==]              
              [==                      DataBase Entry Added! Run Number: 1928, File ID: 0                      ==]              
              [==                                     TRestRun Created ...                                     ==]              
              [==                                         - Path : ./                                          ==]              
              [==                               - Filename : RawData_01928.root                                ==]              
              [==                                            Done!                                             ==]              
jgalan@sultan:~/rest-raw/pipeline/trex$ 
```

**Comment by nkx111** [comment]
> I set verboseLevel to info at run.xml and at 01_raw.rml inside TRestRawSignalAnalysisProcess and at TRestEventRateAnalysisProcess

You should set the verbose level of `TRestProcessRunner` also to `info`

**Review by nkx111 — APPROVED** [review]

**Comment by jgalan** [comment]
One more approval to merge @juanangp or @cmargalejo ?

**Review by cmargalejo — APPROVED** [review]

**Pull request merged**
